# Install script for directory: /home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga

# Set the install prefix
if(NOT DEFINED CMAKE_INSTALL_PREFIX)
  set(CMAKE_INSTALL_PREFIX "/usr/local")
endif()
string(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
if(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  if(BUILD_TYPE)
    string(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  else()
    set(CMAKE_INSTALL_CONFIG_NAME "")
  endif()
  message(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
endif()

# Set the component getting installed.
if(NOT CMAKE_INSTALL_COMPONENT)
  if(COMPONENT)
    message(STATUS "Install component: \"${COMPONENT}\"")
    set(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  else()
    set(CMAKE_INSTALL_COMPONENT)
  endif()
endif()

# Install shared libraries without execute permission?
if(NOT DEFINED CMAKE_INSTALL_SO_NO_EXE)
  set(CMAKE_INSTALL_SO_NO_EXE "1")
endif()

if("${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/qgis/python/plugins/processing/algs/saga" TYPE FILE FILES
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/SagaAlgorithm.py"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/SagaAlgorithmProvider.py"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/SagaDescriptionCreator.py"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/SagaNameDecorator.py"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/SagaUtils.py"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/SplitRGBBands.py"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/__init__.py"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/versioncheck.py"
    )
endif()

if("${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/qgis/python/plugins/processing/algs/saga/description" TYPE FILE FILES
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/AccumulatedCost(Anisotropic).txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/AccumulatedCost(Isotropic).txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/AddCoordinatestopoints.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/AddGridValuestoPoints.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/AddGridValuestoShapes.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/AddPointAttributestoPolygons.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/AddPolygonAttributestoPoints.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/Aggregate.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/AggregatePointObservations.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/AggregationIndex.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/AnalyticalHierarchyProcess.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/AnalyticalHillshading.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/B-SplineApproximation.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/BurnStreamNetworkintoDEM.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/CellBalance.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/ChangeDateFormat.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/ChangeDetection.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/ChangeGridValues.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/ChangeTimeFormat.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/ChannelNetwork.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/ChannelNetworkandDrainageBasins.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/ClipGridwithPolygon.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/ClipPointswithPolygons.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/CloseGaps.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/CloseGapswithSpline.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/CloseOneCellGaps.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/ClusterAnalysisforGrids.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/ConfusionMatrix(GridPolygons).txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/ContourLinesfromGrid.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/ConvergenceIndex(SearchRadius).txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/ConvergenceIndex.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/ConvertDataStorageType.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/ConvertLinestoPoints.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/ConvertLinestoPolygons.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/ConvertMultipointstoPoints.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/ConvertPointstoLine(s).txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/ConvertPolygonLineVerticestoPoints.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/ConvertPolygonstoLines.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/ConvexHull.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/CreateLinesGraticule.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/CreatePolygonsGraticule.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/CropToData.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/Cross-ClassificationandTabulation.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/CrossProfiles.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/CubicSplineApproximation.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/CurvatureClassification.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/CutShapesLayer.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/DTMFilter(slope-based).txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/DiffusiveHillslopeEvolution(ADI).txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/DiffusiveHillslopeEvolution(FTCS).txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/DirectionalStatisticsforSingleGrid.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/DistanceMatrix.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/DiurnalAnisotropicHeating.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/DiversityOfCategories.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/DownslopeDistanceGradient.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/EdgeContamination.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/EffectiveAirFlowHeights.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/FastRegionGrowingAlgorithm.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/FastRepresentativeness.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/FillGapsinRecords.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/FillSinks(PlanchonDarboux,2001).txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/FillSinks(QMofESP).txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/FillSinks(WangLiu).txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/FillSinksXXL(WangLiu).txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/FilterClumps.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/FireRiskAnalysis.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/FitNPointstoshape.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/FlatDetection.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/FlattenPolygonLayer.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/FlowAccumulation(FlowTracing).txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/FlowAccumulation(QMofESP).txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/FlowAccumulation(Recursive).txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/FlowAccumulation(Top-Down).txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/FlowPathLength.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/FlowWidthandSpecificCatchmentArea.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/Fragmentation(Alternative).txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/Fragmentation(Standard).txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/FragmentationClassesfromDensityandConnectivity.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/Function.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/Fuzzify.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/FuzzyIntersection(AND).txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/FuzzyUnion(OR).txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/GaussianFilter.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/GeographicallyWeightedMultipleRegression(Points).txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/GeographicallyWeightedMultipleRegression(PointsGrids).txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/GeographicallyWeightedMultipleRegression.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/GeographicallyWeightedRegression(PointsGrid).txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/GeographicallyWeightedRegression.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/GeometricFigures.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/GetShapesExtents.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/GlobalMoransIforGrids.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/GradientVectorfromCartesiantoPolarCoordinates.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/GradientVectorfromPolartoCartesianCoordinates.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/GradientVectorsfromDirectionalComponents.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/GradientVectorsfromDirectionandLength.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/GradientVectorsfromSurface.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/GridBuffer.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/GridCalculator.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/GridCellIndex.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/GridDifference.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/GridDivision.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/GridMasking.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/GridNormalisation.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/GridOrientation.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/GridProximityBuffer.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/GridSkeletonization.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/GridStandardisation.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/GridStatisticsforPolygons.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/GridValuestoPoints(randomly).txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/GridValuestoPoints.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/GridVolume.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/GridsProduct.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/GridsSum.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/HistogramSurface.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/Hypsometry.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/InverseDistanceWeighted.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/InvertDataNo-Data.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/KernelDensityEstimation.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/LSFactor.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/LakeFlood.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/LandSurfaceTemperature.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/LaplacianFilter.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/Layerofextremevalue.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/LeastCostPaths.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/Line-PolygonIntersection.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/LineDissolve.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/LineProperties.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/LineSimplification.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/LocalMinimaandMaxima.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/MajorityFilter.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/MassBalanceIndex.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/MergeLayers.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/MetricConversions.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/MinimumDistanceAnalysis.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/ModifiedQuadraticShepard.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/MorphologicalFilter.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/MorphometricProtectionIndex.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/Mosaicking.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/Multi-BandVariation.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/MultiDirectionLeeFilter.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/MultilevelB-SplineInterpolation(fromGrid).txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/MultilevelB-SplineInterpolation.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/MultilevelB-SplineInterpolationforCategories.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/MultipleRegressionAnalysis(GridGrids).txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/MultipleRegressionAnalysis(PointsGrids).txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/MultiresolutionIndexofValleyBottomFlatness(MRVBF).txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/NaturalNeighbour.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/NearestNeighbour.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/OrderedWeightedAveraging(OWA).txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/OrdinaryKriging(Global).txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/OrdinaryKriging.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/OverlandFlow-KinematicWaveD8.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/OverlandFlowDistancetoChannelNetwork.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/Patching.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/PatternAnalysis.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/PointStatisticsforPolygons.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/PointsFilter.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/PointsThinning.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/PolartoCartesianCoordinates.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/Polygon-LineIntersection.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/PolygonCentroids.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/PolygonClipping.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/PolygonDifference.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/PolygonDissolve.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/PolygonDissolveAllPolygs.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/PolygonIdentity.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/PolygonIntersect.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/PolygonPartstoSeparatePolygons.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/PolygonProperties.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/PolygonSelfIntersection.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/PolygonShapeIndices.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/PolygonSymmetricalDifference.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/PolygonUnion.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/PolygonUpdate.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/PolygonstoEdgesandNodes.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/PolynomialRegression.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/PrincipleComponentsAnalysis.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/Profilefrompoints.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/ProfilesfromLines.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/ProximityGrid.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/QuadTreeStructuretoShapes.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/RGBComposite.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/RadiusofVariance(Grid).txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/RandomField.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/RandomTerrainGeneration.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/RankFilter.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/RealSurfaceArea.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/ReclassifyGridValues.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/RegressionAnalysis(PointsGrid).txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/RelativeHeightsandSlopePositions.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/RemoveDuplicatePoints.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/Representativeness(Grid).txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/Resampling.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/ResidualAnalysis(Grid).txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/RunningAverage.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/SAGAWetnessIndex.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/SeedGeneration.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/Separatepointsbydirection.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/ShapesBuffer.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/ShapesBufferFixed.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/ShapestoGrid.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/SharedPolygonEdges.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/ShrinkAndExpand.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/SimpleFilter.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/SimpleRegionGrowing.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/Simulation.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/SinkDrainageRouteDetection.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/SinkRemoval.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/SkyViewFactor.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/Slope,Aspect,Curvature.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/SlopeLength.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/SoilTextureClassification.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/SpatialPointPatternAnalysis.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/SplitShapesLayerRandomly.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/StatisticsforGrids.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/StrahlerOrder.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/StreamPowerIndex.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/SuccessiveFlowRouting.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/SupervisedClassification.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/SurfaceSpecificPoints.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/TPIBasedLandformClassification.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/TerrainRuggednessIndex(TRI).txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/ThinPlateSpline(TIN).txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/ThinPlateSpline.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/ThresholdBuffer.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/TopographicCorrection.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/TopographicPositionIndex(TPI).txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/TopographicWetnessIndex(TWI).txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/Transectthroughpolygonshapefile.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/TransformShapes.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/TransposeGrids.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/Triangulation.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/UniversalKriging(Global).txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/UniversalKriging.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/UpslopeArea.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/UserDefinedFilter.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/VariogramCloud.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/VariogramSurface.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/VectorRuggednessMeasure(VRM).txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/VectorisingGridClasses.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/VegetationIndex(SlopeBased).txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/VerticalDistancetoChannelNetwork.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/WaterRetentionCapacity.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/WatershedBasins.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/WatershedSegmentation.txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/WindEffect(WindwardLeewardIndex).txt"
    "/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/description/ZonalGridStatistics.txt"
    )
endif()

if(NOT CMAKE_INSTALL_LOCAL_ONLY)
  # Include the install script for each subdirectory.
  include("/home/danilo/dev/cpp/QGIS/python/plugins/processing/algs/saga/ext/cmake_install.cmake")

endif()

