FILE(MAKE_DIRECTORY "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/db_plugins/postgis")
FILE(COPY "/home/danilo/dev/cpp/QGIS/python/plugins/db_manager/db_plugins/postgis/__init__.py" DESTINATION "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/db_plugins/postgis")
FILE(COPY "/home/danilo/dev/cpp/QGIS/python/plugins/db_manager/db_plugins/postgis/connector.py" DESTINATION "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/db_plugins/postgis")
FILE(COPY "/home/danilo/dev/cpp/QGIS/python/plugins/db_manager/db_plugins/postgis/data_model.py" DESTINATION "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/db_plugins/postgis")
FILE(COPY "/home/danilo/dev/cpp/QGIS/python/plugins/db_manager/db_plugins/postgis/info_model.py" DESTINATION "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/db_plugins/postgis")
FILE(COPY "/home/danilo/dev/cpp/QGIS/python/plugins/db_manager/db_plugins/postgis/plugin.py" DESTINATION "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/db_plugins/postgis")
FILE(COPY "/home/danilo/dev/cpp/QGIS/python/plugins/db_manager/db_plugins/postgis/sql_dictionary.py" DESTINATION "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/db_plugins/postgis")
FILE(COPY "/home/danilo/dev/cpp/QGIS/python/plugins/db_manager/db_plugins/postgis/resources_rc.py" DESTINATION "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/db_plugins/postgis")
FILE(MAKE_DIRECTORY "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/db_plugins/postgis/icons")
FILE(COPY "/home/danilo/dev/cpp/QGIS/python/plugins/db_manager/db_plugins/postgis/icons/postgis_elephant.png" DESTINATION "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/db_plugins/postgis/icons")
FILE(MAKE_DIRECTORY "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/db_plugins/postgis/plugins/qgis_topoview/templates")
FILE(COPY "/home/danilo/dev/cpp/QGIS/python/plugins/db_manager/db_plugins/postgis/plugins/qgis_topoview/templates/edge.qml" DESTINATION "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/db_plugins/postgis/plugins/qgis_topoview/templates")
FILE(COPY "/home/danilo/dev/cpp/QGIS/python/plugins/db_manager/db_plugins/postgis/plugins/qgis_topoview/templates/edge_label.qml" DESTINATION "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/db_plugins/postgis/plugins/qgis_topoview/templates")
FILE(COPY "/home/danilo/dev/cpp/QGIS/python/plugins/db_manager/db_plugins/postgis/plugins/qgis_topoview/templates/face.qml" DESTINATION "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/db_plugins/postgis/plugins/qgis_topoview/templates")
FILE(COPY "/home/danilo/dev/cpp/QGIS/python/plugins/db_manager/db_plugins/postgis/plugins/qgis_topoview/templates/face_left.qml" DESTINATION "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/db_plugins/postgis/plugins/qgis_topoview/templates")
FILE(COPY "/home/danilo/dev/cpp/QGIS/python/plugins/db_manager/db_plugins/postgis/plugins/qgis_topoview/templates/face_mbr.qml" DESTINATION "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/db_plugins/postgis/plugins/qgis_topoview/templates")
FILE(COPY "/home/danilo/dev/cpp/QGIS/python/plugins/db_manager/db_plugins/postgis/plugins/qgis_topoview/templates/face_right.qml" DESTINATION "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/db_plugins/postgis/plugins/qgis_topoview/templates")
FILE(COPY "/home/danilo/dev/cpp/QGIS/python/plugins/db_manager/db_plugins/postgis/plugins/qgis_topoview/templates/face_seed.qml" DESTINATION "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/db_plugins/postgis/plugins/qgis_topoview/templates")
FILE(COPY "/home/danilo/dev/cpp/QGIS/python/plugins/db_manager/db_plugins/postgis/plugins/qgis_topoview/templates/next_left.qml" DESTINATION "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/db_plugins/postgis/plugins/qgis_topoview/templates")
FILE(COPY "/home/danilo/dev/cpp/QGIS/python/plugins/db_manager/db_plugins/postgis/plugins/qgis_topoview/templates/next_right.qml" DESTINATION "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/db_plugins/postgis/plugins/qgis_topoview/templates")
FILE(COPY "/home/danilo/dev/cpp/QGIS/python/plugins/db_manager/db_plugins/postgis/plugins/qgis_topoview/templates/node.qml" DESTINATION "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/db_plugins/postgis/plugins/qgis_topoview/templates")
FILE(COPY "/home/danilo/dev/cpp/QGIS/python/plugins/db_manager/db_plugins/postgis/plugins/qgis_topoview/templates/node_label.qml" DESTINATION "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/db_plugins/postgis/plugins/qgis_topoview/templates")
FILE(MAKE_DIRECTORY "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/db_plugins/postgis/plugins/qgis_topoview")
FILE(COPY "/home/danilo/dev/cpp/QGIS/python/plugins/db_manager/db_plugins/postgis/plugins/qgis_topoview/__init__.py" DESTINATION "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/db_plugins/postgis/plugins/qgis_topoview")
FILE(MAKE_DIRECTORY "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/db_plugins/postgis/plugins/versioning")
FILE(COPY "/home/danilo/dev/cpp/QGIS/python/plugins/db_manager/db_plugins/postgis/plugins/versioning/__init__.py" DESTINATION "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/db_plugins/postgis/plugins/versioning")
FILE(COPY "/home/danilo/dev/cpp/QGIS/python/plugins/db_manager/db_plugins/postgis/plugins/versioning/dlg_versioning.py" DESTINATION "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/db_plugins/postgis/plugins/versioning")
FILE(COPY "/home/danilo/dev/cpp/QGIS/python/plugins/db_manager/db_plugins/postgis/plugins/versioning/ui_DlgVersioning.py" DESTINATION "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/db_plugins/postgis/plugins/versioning")
FILE(MAKE_DIRECTORY "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/db_plugins/postgis/plugins")
FILE(COPY "/home/danilo/dev/cpp/QGIS/python/plugins/db_manager/db_plugins/postgis/plugins/__init__.py" DESTINATION "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/db_plugins/postgis/plugins")
FILE(MAKE_DIRECTORY "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/db_plugins/spatialite")
FILE(COPY "/home/danilo/dev/cpp/QGIS/python/plugins/db_manager/db_plugins/spatialite/__init__.py" DESTINATION "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/db_plugins/spatialite")
FILE(COPY "/home/danilo/dev/cpp/QGIS/python/plugins/db_manager/db_plugins/spatialite/connector.py" DESTINATION "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/db_plugins/spatialite")
FILE(COPY "/home/danilo/dev/cpp/QGIS/python/plugins/db_manager/db_plugins/spatialite/data_model.py" DESTINATION "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/db_plugins/spatialite")
FILE(COPY "/home/danilo/dev/cpp/QGIS/python/plugins/db_manager/db_plugins/spatialite/info_model.py" DESTINATION "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/db_plugins/spatialite")
FILE(COPY "/home/danilo/dev/cpp/QGIS/python/plugins/db_manager/db_plugins/spatialite/plugin.py" DESTINATION "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/db_plugins/spatialite")
FILE(COPY "/home/danilo/dev/cpp/QGIS/python/plugins/db_manager/db_plugins/spatialite/sql_dictionary.py" DESTINATION "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/db_plugins/spatialite")
FILE(COPY "/home/danilo/dev/cpp/QGIS/python/plugins/db_manager/db_plugins/spatialite/resources_rc.py" DESTINATION "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/db_plugins/spatialite")
FILE(MAKE_DIRECTORY "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/db_plugins/spatialite/icons")
FILE(COPY "/home/danilo/dev/cpp/QGIS/python/plugins/db_manager/db_plugins/spatialite/icons/spatialite_icon.png" DESTINATION "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/db_plugins/spatialite/icons")
FILE(MAKE_DIRECTORY "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/db_plugins/gpkg")
FILE(COPY "/home/danilo/dev/cpp/QGIS/python/plugins/db_manager/db_plugins/gpkg/__init__.py" DESTINATION "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/db_plugins/gpkg")
FILE(COPY "/home/danilo/dev/cpp/QGIS/python/plugins/db_manager/db_plugins/gpkg/connector.py" DESTINATION "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/db_plugins/gpkg")
FILE(COPY "/home/danilo/dev/cpp/QGIS/python/plugins/db_manager/db_plugins/gpkg/data_model.py" DESTINATION "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/db_plugins/gpkg")
FILE(COPY "/home/danilo/dev/cpp/QGIS/python/plugins/db_manager/db_plugins/gpkg/info_model.py" DESTINATION "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/db_plugins/gpkg")
FILE(COPY "/home/danilo/dev/cpp/QGIS/python/plugins/db_manager/db_plugins/gpkg/plugin.py" DESTINATION "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/db_plugins/gpkg")
FILE(COPY "/home/danilo/dev/cpp/QGIS/python/plugins/db_manager/db_plugins/gpkg/sql_dictionary.py" DESTINATION "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/db_plugins/gpkg")
FILE(COPY "/home/danilo/dev/cpp/QGIS/python/plugins/db_manager/db_plugins/gpkg/resources_rc.py" DESTINATION "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/db_plugins/gpkg")
FILE(MAKE_DIRECTORY "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/db_plugins/gpkg/icons")
FILE(COPY "/home/danilo/dev/cpp/QGIS/python/plugins/db_manager/db_plugins/gpkg/icons/gpkg_icon.png" DESTINATION "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/db_plugins/gpkg/icons")
FILE(MAKE_DIRECTORY "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/db_plugins/vlayers")
FILE(COPY "/home/danilo/dev/cpp/QGIS/python/plugins/db_manager/db_plugins/vlayers/__init__.py" DESTINATION "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/db_plugins/vlayers")
FILE(COPY "/home/danilo/dev/cpp/QGIS/python/plugins/db_manager/db_plugins/vlayers/connector.py" DESTINATION "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/db_plugins/vlayers")
FILE(COPY "/home/danilo/dev/cpp/QGIS/python/plugins/db_manager/db_plugins/vlayers/data_model.py" DESTINATION "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/db_plugins/vlayers")
FILE(COPY "/home/danilo/dev/cpp/QGIS/python/plugins/db_manager/db_plugins/vlayers/info_model.py" DESTINATION "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/db_plugins/vlayers")
FILE(COPY "/home/danilo/dev/cpp/QGIS/python/plugins/db_manager/db_plugins/vlayers/plugin.py" DESTINATION "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/db_plugins/vlayers")
FILE(COPY "/home/danilo/dev/cpp/QGIS/python/plugins/db_manager/db_plugins/vlayers/sql_dictionary.py" DESTINATION "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/db_plugins/vlayers")
FILE(COPY "/home/danilo/dev/cpp/QGIS/python/plugins/db_manager/db_plugins/vlayers/resources_rc.py" DESTINATION "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/db_plugins/vlayers")
FILE(MAKE_DIRECTORY "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/db_plugins")
FILE(COPY "/home/danilo/dev/cpp/QGIS/python/plugins/db_manager/db_plugins/__init__.py" DESTINATION "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/db_plugins")
FILE(COPY "/home/danilo/dev/cpp/QGIS/python/plugins/db_manager/db_plugins/connector.py" DESTINATION "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/db_plugins")
FILE(COPY "/home/danilo/dev/cpp/QGIS/python/plugins/db_manager/db_plugins/data_model.py" DESTINATION "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/db_plugins")
FILE(COPY "/home/danilo/dev/cpp/QGIS/python/plugins/db_manager/db_plugins/html_elems.py" DESTINATION "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/db_plugins")
FILE(COPY "/home/danilo/dev/cpp/QGIS/python/plugins/db_manager/db_plugins/info_model.py" DESTINATION "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/db_plugins")
FILE(COPY "/home/danilo/dev/cpp/QGIS/python/plugins/db_manager/db_plugins/plugin.py" DESTINATION "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/db_plugins")
FILE(MAKE_DIRECTORY "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/icons")
FILE(COPY "/home/danilo/dev/cpp/QGIS/python/plugins/db_manager/icons/sql.gif" DESTINATION "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/icons")
FILE(COPY "/home/danilo/dev/cpp/QGIS/python/plugins/db_manager/icons/about.png" DESTINATION "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/icons")
FILE(COPY "/home/danilo/dev/cpp/QGIS/python/plugins/db_manager/icons/dbmanager.png" DESTINATION "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/icons")
FILE(COPY "/home/danilo/dev/cpp/QGIS/python/plugins/db_manager/icons/layer_line.png" DESTINATION "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/icons")
FILE(COPY "/home/danilo/dev/cpp/QGIS/python/plugins/db_manager/icons/layer_point.png" DESTINATION "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/icons")
FILE(COPY "/home/danilo/dev/cpp/QGIS/python/plugins/db_manager/icons/layer_polygon.png" DESTINATION "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/icons")
FILE(COPY "/home/danilo/dev/cpp/QGIS/python/plugins/db_manager/icons/layer_raster.png" DESTINATION "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/icons")
FILE(COPY "/home/danilo/dev/cpp/QGIS/python/plugins/db_manager/icons/layer_unknown.png" DESTINATION "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/icons")
FILE(COPY "/home/danilo/dev/cpp/QGIS/python/plugins/db_manager/icons/namespace.png" DESTINATION "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/icons")
FILE(COPY "/home/danilo/dev/cpp/QGIS/python/plugins/db_manager/icons/plugged.png" DESTINATION "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/icons")
FILE(COPY "/home/danilo/dev/cpp/QGIS/python/plugins/db_manager/icons/table.png" DESTINATION "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/icons")
FILE(COPY "/home/danilo/dev/cpp/QGIS/python/plugins/db_manager/icons/unplugged.png" DESTINATION "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/icons")
FILE(COPY "/home/danilo/dev/cpp/QGIS/python/plugins/db_manager/icons/view.png" DESTINATION "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/icons")
FILE(COPY "/home/danilo/dev/cpp/QGIS/python/plugins/db_manager/icons/view_materialized.png" DESTINATION "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/icons")
FILE(COPY "/home/danilo/dev/cpp/QGIS/python/plugins/db_manager/icons/warning-20px.png" DESTINATION "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/icons")
FILE(COPY "/home/danilo/dev/cpp/QGIS/python/plugins/db_manager/icons/namespaces.xpm" DESTINATION "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/icons")
FILE(COPY "/home/danilo/dev/cpp/QGIS/python/plugins/db_manager/icons/tables.xpm" DESTINATION "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/icons")
FILE(COPY "/home/danilo/dev/cpp/QGIS/python/plugins/db_manager/icons/user.xpm" DESTINATION "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/icons")
FILE(COPY "/home/danilo/dev/cpp/QGIS/python/plugins/db_manager/icons/users.xpm" DESTINATION "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/icons")
FILE(COPY "/home/danilo/dev/cpp/QGIS/python/plugins/db_manager/icons/toolbar/action_del_table.png" DESTINATION "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/icons")
FILE(COPY "/home/danilo/dev/cpp/QGIS/python/plugins/db_manager/icons/toolbar/action_delete.png" DESTINATION "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/icons")
FILE(COPY "/home/danilo/dev/cpp/QGIS/python/plugins/db_manager/icons/toolbar/action_edit_table.png" DESTINATION "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/icons")
FILE(COPY "/home/danilo/dev/cpp/QGIS/python/plugins/db_manager/icons/toolbar/action_export.png" DESTINATION "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/icons")
FILE(COPY "/home/danilo/dev/cpp/QGIS/python/plugins/db_manager/icons/toolbar/action_import.png" DESTINATION "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/icons")
FILE(COPY "/home/danilo/dev/cpp/QGIS/python/plugins/db_manager/icons/toolbar/action_new_table.png" DESTINATION "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/icons")
FILE(COPY "/home/danilo/dev/cpp/QGIS/python/plugins/db_manager/icons/toolbar/action_refresh.png" DESTINATION "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/icons")
FILE(COPY "/home/danilo/dev/cpp/QGIS/python/plugins/db_manager/icons/toolbar/action_sql_window.png" DESTINATION "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/icons")
FILE(MAKE_DIRECTORY "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/.")
FILE(COPY "/home/danilo/dev/cpp/QGIS/python/plugins/db_manager/LICENSE" DESTINATION "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/.")
FILE(COPY "/home/danilo/dev/cpp/QGIS/python/plugins/db_manager/TODO" DESTINATION "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/.")
FILE(COPY "/home/danilo/dev/cpp/QGIS/python/plugins/db_manager/__init__.py" DESTINATION "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/.")
FILE(COPY "/home/danilo/dev/cpp/QGIS/python/plugins/db_manager/db_manager.py" DESTINATION "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/.")
FILE(COPY "/home/danilo/dev/cpp/QGIS/python/plugins/db_manager/db_manager_plugin.py" DESTINATION "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/.")
FILE(COPY "/home/danilo/dev/cpp/QGIS/python/plugins/db_manager/db_model.py" DESTINATION "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/.")
FILE(COPY "/home/danilo/dev/cpp/QGIS/python/plugins/db_manager/db_tree.py" DESTINATION "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/.")
FILE(COPY "/home/danilo/dev/cpp/QGIS/python/plugins/db_manager/dlg_add_geometry_column.py" DESTINATION "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/.")
FILE(COPY "/home/danilo/dev/cpp/QGIS/python/plugins/db_manager/dlg_create_constraint.py" DESTINATION "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/.")
FILE(COPY "/home/danilo/dev/cpp/QGIS/python/plugins/db_manager/dlg_create_index.py" DESTINATION "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/.")
FILE(COPY "/home/danilo/dev/cpp/QGIS/python/plugins/db_manager/dlg_create_table.py" DESTINATION "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/.")
FILE(COPY "/home/danilo/dev/cpp/QGIS/python/plugins/db_manager/dlg_db_error.py" DESTINATION "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/.")
FILE(COPY "/home/danilo/dev/cpp/QGIS/python/plugins/db_manager/dlg_export_vector.py" DESTINATION "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/.")
FILE(COPY "/home/danilo/dev/cpp/QGIS/python/plugins/db_manager/dlg_field_properties.py" DESTINATION "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/.")
FILE(COPY "/home/danilo/dev/cpp/QGIS/python/plugins/db_manager/dlg_import_vector.py" DESTINATION "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/.")
FILE(COPY "/home/danilo/dev/cpp/QGIS/python/plugins/db_manager/dlg_query_builder.py" DESTINATION "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/.")
FILE(COPY "/home/danilo/dev/cpp/QGIS/python/plugins/db_manager/dlg_sql_layer_window.py" DESTINATION "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/.")
FILE(COPY "/home/danilo/dev/cpp/QGIS/python/plugins/db_manager/dlg_sql_window.py" DESTINATION "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/.")
FILE(COPY "/home/danilo/dev/cpp/QGIS/python/plugins/db_manager/dlg_table_properties.py" DESTINATION "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/.")
FILE(COPY "/home/danilo/dev/cpp/QGIS/python/plugins/db_manager/info_viewer.py" DESTINATION "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/.")
FILE(COPY "/home/danilo/dev/cpp/QGIS/python/plugins/db_manager/layer_preview.py" DESTINATION "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/.")
FILE(COPY "/home/danilo/dev/cpp/QGIS/python/plugins/db_manager/sql_dictionary.py" DESTINATION "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/.")
FILE(COPY "/home/danilo/dev/cpp/QGIS/python/plugins/db_manager/sqledit.py" DESTINATION "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/.")
FILE(COPY "/home/danilo/dev/cpp/QGIS/python/plugins/db_manager/table_viewer.py" DESTINATION "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/.")
FILE(COPY "/home/danilo/dev/cpp/QGIS/python/plugins/db_manager/resources_rc.py" DESTINATION "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/.")
FILE(COPY "/home/danilo/dev/cpp/QGIS/python/plugins/db_manager/metadata.txt" DESTINATION "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/.")
FILE(MAKE_DIRECTORY "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/ui")
FILE(COPY "/home/danilo/dev/cpp/QGIS/python/plugins/db_manager/ui_DlgAddGeometryColumn.py" DESTINATION "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/ui")
FILE(COPY "/home/danilo/dev/cpp/QGIS/python/plugins/db_manager/ui_DlgCreateConstraint.py" DESTINATION "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/ui")
FILE(COPY "/home/danilo/dev/cpp/QGIS/python/plugins/db_manager/ui_DlgCreateIndex.py" DESTINATION "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/ui")
FILE(COPY "/home/danilo/dev/cpp/QGIS/python/plugins/db_manager/ui_DlgCreateTable.py" DESTINATION "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/ui")
FILE(COPY "/home/danilo/dev/cpp/QGIS/python/plugins/db_manager/ui_DlgDbError.py" DESTINATION "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/ui")
FILE(COPY "/home/danilo/dev/cpp/QGIS/python/plugins/db_manager/ui_DlgExportVector.py" DESTINATION "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/ui")
FILE(COPY "/home/danilo/dev/cpp/QGIS/python/plugins/db_manager/ui_DlgFieldProperties.py" DESTINATION "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/ui")
FILE(COPY "/home/danilo/dev/cpp/QGIS/python/plugins/db_manager/ui_DlgImportVector.py" DESTINATION "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/ui")
FILE(COPY "/home/danilo/dev/cpp/QGIS/python/plugins/db_manager/ui_DlgQueryBuilder.py" DESTINATION "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/ui")
FILE(COPY "/home/danilo/dev/cpp/QGIS/python/plugins/db_manager/ui_DlgSqlLayerWindow.py" DESTINATION "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/ui")
FILE(COPY "/home/danilo/dev/cpp/QGIS/python/plugins/db_manager/ui_DlgSqlWindow.py" DESTINATION "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/ui")
FILE(COPY "/home/danilo/dev/cpp/QGIS/python/plugins/db_manager/ui_DlgTableProperties.py" DESTINATION "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/ui")
FILE(COPY "/home/danilo/dev/cpp/QGIS/python/plugins/db_manager/ui/__init__.py" DESTINATION "/home/danilo/dev/cpp/QGIS/output/python/plugins/db_manager/ui")
